name: Vercel Production Deployment 🚀
on:
  push:
    branches:
      - vercel-production
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-args: '--prod'
          working-directory: ./
