name: Create PR from [development] branch

on:
  push:
    branches:
      - development

jobs:
  development-PR:
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create PR
        run: gh pr create --title "${{ github.event.head_commit.message }}" --body ""
