name: Merge PR from development branch

on:
  pull_request:
    types:
      - opened

jobs:
  Merge-PR:
    if: ${{ github.head_ref == 'development' }}
    runs-on: ubuntu-latest
    permissions: write-all
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Merge PR
        run: gh pr merge ${{ github.event.number }} --merge
